'use client';

import { useState, useTransition } from 'react';
import Image from 'next/image';
import { approveInvoice } from '@/app/actions/invoice-approval';
import {
  NAVY,
  GOLD,
  GOLD_HOVER,
  SURFACE,
  SURFACE_LIGHT,
  CARD,
  TEXT_MID,
  TEXT_MUTED,
  SUCCESS,
  SUCCESS_BG,
  ERROR,
  ERROR_BG,
  INFO,
  INFO_BG,
  neu,
} from '@/lib/theme';

// ============================================================================
// TYPES
// ============================================================================

interface InvoiceData {
  id: string;
  invoiceNumber: string;
  type: 'estimate' | 'invoice';
  status: string;
  clientName: string;
  clientEmail: string | null;
  clientPhone: string | null;
  clientAddress: string | null;
  language: string;
  taxRate: number;
  gstNumber: string;
  subtotalCents: number;
  taxCents: number;
  totalCents: number;
  notes: string | null;
  invoiceDate: string;
  dueDate: string | null;
  approvedAt: string | null;
  shareToken: string;
}

interface LineItem {
  id: string;
  sectionType: string | null;
  label: string;
  description: string;
  rateCents: number;
  quantity: number;
  amountCents: number;
  footerLines: string[];
}

interface Milestone {
  id: string;
  label: string;
  labelZh: string | null;
  percentage: number;
  amountCents: number;
  isPaid: boolean;
  paidAt: string | null;
}

interface CompanyInfo {
  name: string;
  phone: string;
  email: string;
  address: string;
  logo: string;
}

interface InvoiceClientViewProps {
  invoice: InvoiceData;
  lineItems: LineItem[];
  milestones: Milestone[];
  terms: string;
  company: CompanyInfo;
  canApprove: boolean;
  locale: string;
}

// ============================================================================
// HELPERS
// ============================================================================

function formatCurrency(cents: number): string {
  return new Intl.NumberFormat('en-CA', {
    style: 'currency',
    currency: 'CAD',
    minimumFractionDigits: 2,
  }).format(cents / 100);
}

function formatDate(iso: string, locale: string): string {
  return new Date(iso).toLocaleDateString(
    locale === 'zh' ? 'zh-CN' : 'en-CA',
    { year: 'numeric', month: 'long', day: 'numeric' }
  );
}

function getStatusLabel(status: string, locale: string): string {
  const labels: Record<string, Record<string, string>> = {
    draft: { en: 'Draft', zh: '草稿' },
    sent: { en: 'Sent', zh: '已发送' },
    viewed: { en: 'Viewed', zh: '已查看' },
    approved: { en: 'Approved', zh: '已批准' },
    in_progress: { en: 'In Progress', zh: '进行中' },
    completed: { en: 'Completed', zh: '已完成' },
    paid: { en: 'Paid', zh: '已支付' },
    void: { en: 'Void', zh: '已作废' },
  };
  const lang = locale === 'zh' ? 'zh' : 'en';
  return labels[status]?.[lang] ?? status;
}

function getStatusColor(status: string): { bg: string; text: string } {
  switch (status) {
    case 'approved':
    case 'paid':
    case 'completed':
      return { bg: SUCCESS_BG, text: SUCCESS };
    case 'void':
      return { bg: ERROR_BG, text: ERROR };
    case 'viewed':
    case 'in_progress':
      return { bg: INFO_BG, text: INFO };
    default:
      return { bg: 'rgba(27,54,93,0.08)', text: TEXT_MID };
  }
}

/** Translate common UI labels */
function t(key: string, locale: string): string {
  const translations: Record<string, Record<string, string>> = {
    estimate: { en: 'Estimate', zh: '报价单' },
    invoice: { en: 'Invoice', zh: '发票' },
    date: { en: 'Date', zh: '日期' },
    dueDate: { en: 'Due Date', zh: '到期日' },
    status: { en: 'Status', zh: '状态' },
    billTo: { en: 'Bill To', zh: '客户信息' },
    description: { en: 'Description', zh: '描述' },
    amount: { en: 'Amount', zh: '金额' },
    subtotal: { en: 'Subtotal', zh: '小计' },
    gst: { en: 'GST', zh: 'GST 税' },
    total: { en: 'Total', zh: '总计' },
    paymentSchedule: { en: 'Payment Schedule', zh: '付款计划' },
    milestone: { en: 'Milestone', zh: '付款节点' },
    percentage: { en: '%', zh: '%' },
    paid: { en: 'Paid', zh: '已付' },
    unpaid: { en: 'Unpaid', zh: '未付' },
    notes: { en: 'Notes', zh: '备注' },
    terms: { en: 'Terms & Conditions', zh: '条款与条件' },
    approve: { en: 'Approve', zh: '批准' },
    approving: { en: 'Approving...', zh: '批准中...' },
    approved: { en: 'Approved', zh: '已批准' },
    approvedOn: { en: 'Approved on', zh: '批准日期' },
    downloadPdf: { en: 'Download PDF', zh: '下载 PDF' },
    generatedBy: { en: 'Generated by', zh: '由以下公司生成' },
    gstNumber: { en: 'GST #', zh: 'GST 编号' },
    phone: { en: 'Phone', zh: '电话' },
    email: { en: 'Email', zh: '邮箱' },
    itemNumber: { en: '#', zh: '#' },
  };
  const lang = locale === 'zh' ? 'zh' : 'en';
  return translations[key]?.[lang] ?? key;
}

// ============================================================================
// COMPONENT
// ============================================================================

export default function InvoiceClientView({
  invoice,
  lineItems,
  milestones,
  terms,
  company,
  canApprove,
  locale,
}: InvoiceClientViewProps) {
  const [isPending, startTransition] = useTransition();
  const [approvalState, setApprovalState] = useState<{
    approved: boolean;
    error: string | null;
  }>({
    approved: invoice.status === 'approved',
    error: null,
  });
  const [termsOpen, setTermsOpen] = useState(false);

  const typeLabel = t(invoice.type, locale);
  const statusColors = getStatusColor(
    approvalState.approved ? 'approved' : invoice.status
  );

  function handleApprove() {
    startTransition(async () => {
      const result = await approveInvoice(invoice.shareToken);
      if (result.success) {
        setApprovalState({ approved: true, error: null });
      } else {
        setApprovalState((prev) => ({ ...prev, error: result.message }));
      }
    });
  }

  return (
    <div
      style={{ backgroundColor: SURFACE, minHeight: '100vh' }}
      className="pb-12 print:bg-white print:pb-0"
    >
      {/* Container */}
      <div className="mx-auto max-w-3xl px-4 py-8 print:max-w-none print:px-0 print:py-0">
        {/* Main card */}
        <div
          className="rounded-2xl p-8 print:rounded-none print:p-0 print:shadow-none"
          style={{
            backgroundColor: SURFACE_LIGHT,
            boxShadow: neu(8),
          }}
        >
          {/* ============================================================ */}
          {/* COMPANY HEADER                                               */}
          {/* ============================================================ */}
          <header className="mb-8 flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-start sm:justify-between" style={{ borderColor: 'rgba(27,54,93,0.12)' }}>
            <div className="flex items-center gap-4">
              {company.logo && (
                <Image
                  src={company.logo}
                  alt={company.name}
                  width={64}
                  height={64}
                  className="h-16 w-16 rounded-lg object-contain print:h-12 print:w-12"
                  unoptimized
                />
              )}
              <div>
                <h1
                  className="text-2xl font-bold print:text-xl"
                  style={{ color: NAVY }}
                >
                  {company.name}
                </h1>
                <p className="text-sm" style={{ color: TEXT_MID }}>
                  {company.address}
                </p>
              </div>
            </div>
            <div className="text-sm sm:text-right" style={{ color: TEXT_MID }}>
              <p>{t('phone', locale)}: {company.phone}</p>
              <p>{t('email', locale)}: {company.email}</p>
              <p>{t('gstNumber', locale)}: {invoice.gstNumber}</p>
            </div>
          </header>

          {/* ============================================================ */}
          {/* DOCUMENT INFO                                                */}
          {/* ============================================================ */}
          <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <h2
                className="text-xl font-bold uppercase tracking-wide"
                style={{ color: NAVY }}
              >
                {typeLabel} {invoice.invoiceNumber}
              </h2>
              <div className="mt-2 flex flex-wrap items-center gap-3 text-sm" style={{ color: TEXT_MID }}>
                <span>
                  {t('date', locale)}: {formatDate(invoice.invoiceDate, locale)}
                </span>
                {invoice.dueDate && (
                  <span>
                    {t('dueDate', locale)}: {formatDate(invoice.dueDate, locale)}
                  </span>
                )}
              </div>
            </div>
            <div
              className="inline-flex items-center rounded-full px-3 py-1 text-sm font-semibold"
              style={{
                backgroundColor: statusColors.bg,
                color: statusColors.text,
              }}
            >
              {getStatusLabel(
                approvalState.approved ? 'approved' : invoice.status,
                locale
              )}
            </div>
          </div>

          {/* ============================================================ */}
          {/* CLIENT INFO                                                  */}
          {/* ============================================================ */}
          <div
            className="mb-8 rounded-xl p-5"
            style={{ backgroundColor: CARD }}
          >
            <h3
              className="mb-2 text-xs font-semibold uppercase tracking-wider"
              style={{ color: TEXT_MUTED }}
            >
              {t('billTo', locale)}
            </h3>
            <p className="font-semibold" style={{ color: NAVY }}>
              {invoice.clientName}
            </p>
            {invoice.clientAddress && (
              <p className="text-sm" style={{ color: TEXT_MID }}>
                {invoice.clientAddress}
              </p>
            )}
            <div className="mt-1 flex flex-wrap gap-4 text-sm" style={{ color: TEXT_MID }}>
              {invoice.clientPhone && <span>{invoice.clientPhone}</span>}
              {invoice.clientEmail && <span>{invoice.clientEmail}</span>}
            </div>
          </div>

          {/* ============================================================ */}
          {/* LINE ITEMS                                                   */}
          {/* ============================================================ */}
          <div className="mb-8">
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr
                    className="border-b text-left"
                    style={{ borderColor: 'rgba(27,54,93,0.15)' }}
                  >
                    <th
                      className="pb-2 pr-2 text-xs font-semibold uppercase tracking-wider"
                      style={{ color: TEXT_MUTED, width: '2rem' }}
                    >
                      {t('itemNumber', locale)}
                    </th>
                    <th
                      className="pb-2 pr-4 text-xs font-semibold uppercase tracking-wider"
                      style={{ color: TEXT_MUTED }}
                    >
                      {t('description', locale)}
                    </th>
                    <th
                      className="pb-2 text-right text-xs font-semibold uppercase tracking-wider"
                      style={{ color: TEXT_MUTED, whiteSpace: 'nowrap' }}
                    >
                      {t('amount', locale)}
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {lineItems.map((item, idx) => {
                    const isSection =
                      item.sectionType && item.amountCents === 0;

                    if (isSection) {
                      return (
                        <tr key={item.id}>
                          <td
                            colSpan={3}
                            className="pb-1 pt-5 text-sm font-bold uppercase tracking-wide"
                            style={{ color: GOLD }}
                          >
                            {item.label}
                          </td>
                        </tr>
                      );
                    }

                    return (
                      <tr
                        key={item.id}
                        className="border-b"
                        style={{ borderColor: 'rgba(27,54,93,0.06)' }}
                      >
                        <td
                          className="py-3 pr-2 align-top text-xs"
                          style={{ color: TEXT_MUTED }}
                        >
                          {idx + 1}
                        </td>
                        <td className="py-3 pr-4 align-top">
                          <p
                            className="font-medium"
                            style={{ color: NAVY }}
                          >
                            {item.label}
                          </p>
                          {item.description && (
                            <div
                              className="mt-1 whitespace-pre-line text-xs leading-relaxed"
                              style={{ color: TEXT_MID }}
                            >
                              {item.description}
                            </div>
                          )}
                          {item.footerLines && item.footerLines.length > 0 && (
                            <div className="mt-1 text-xs italic" style={{ color: TEXT_MUTED }}>
                              {item.footerLines.map((line, i) => (
                                <p key={i}>{line}</p>
                              ))}
                            </div>
                          )}
                        </td>
                        <td
                          className="py-3 align-top text-right font-medium"
                          style={{ color: NAVY, whiteSpace: 'nowrap' }}
                        >
                          {formatCurrency(item.amountCents)}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* ============================================================ */}
          {/* TOTALS                                                       */}
          {/* ============================================================ */}
          <div className="mb-8 flex justify-end">
            <div className="w-full max-w-xs">
              <div
                className="flex justify-between border-b py-2 text-sm"
                style={{ borderColor: 'rgba(27,54,93,0.1)', color: TEXT_MID }}
              >
                <span>{t('subtotal', locale)}</span>
                <span style={{ color: NAVY }}>
                  {formatCurrency(invoice.subtotalCents)}
                </span>
              </div>
              <div
                className="flex justify-between border-b py-2 text-sm"
                style={{ borderColor: 'rgba(27,54,93,0.1)', color: TEXT_MID }}
              >
                <span>
                  {t('gst', locale)} ({invoice.taxRate}%)
                </span>
                <span style={{ color: NAVY }}>
                  {formatCurrency(invoice.taxCents)}
                </span>
              </div>
              <div
                className="flex justify-between py-3 text-lg font-bold"
                style={{ color: NAVY }}
              >
                <span>{t('total', locale)}</span>
                <span>{formatCurrency(invoice.totalCents)}</span>
              </div>
            </div>
          </div>

          {/* ============================================================ */}
          {/* PAYMENT SCHEDULE                                             */}
          {/* ============================================================ */}
          {milestones.length > 0 && (
            <div className="mb-8">
              <h3
                className="mb-3 text-sm font-semibold uppercase tracking-wider"
                style={{ color: TEXT_MUTED }}
              >
                {t('paymentSchedule', locale)}
              </h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr
                      className="border-b text-left"
                      style={{ borderColor: 'rgba(27,54,93,0.15)' }}
                    >
                      <th
                        className="pb-2 pr-4 text-xs font-semibold uppercase tracking-wider"
                        style={{ color: TEXT_MUTED }}
                      >
                        {t('milestone', locale)}
                      </th>
                      <th
                        className="pb-2 pr-4 text-center text-xs font-semibold uppercase tracking-wider"
                        style={{ color: TEXT_MUTED }}
                      >
                        {t('percentage', locale)}
                      </th>
                      <th
                        className="pb-2 pr-4 text-right text-xs font-semibold uppercase tracking-wider"
                        style={{ color: TEXT_MUTED }}
                      >
                        {t('amount', locale)}
                      </th>
                      <th
                        className="pb-2 text-center text-xs font-semibold uppercase tracking-wider"
                        style={{ color: TEXT_MUTED }}
                      >
                        {t('status', locale)}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {milestones.map((ms) => (
                      <tr
                        key={ms.id}
                        className="border-b"
                        style={{ borderColor: 'rgba(27,54,93,0.06)' }}
                      >
                        <td className="py-3 pr-4" style={{ color: NAVY }}>
                          {locale === 'zh' && ms.labelZh
                            ? ms.labelZh
                            : ms.label}
                        </td>
                        <td
                          className="py-3 pr-4 text-center"
                          style={{ color: TEXT_MID }}
                        >
                          {ms.percentage}%
                        </td>
                        <td
                          className="py-3 pr-4 text-right font-medium"
                          style={{ color: NAVY }}
                        >
                          {formatCurrency(ms.amountCents)}
                        </td>
                        <td className="py-3 text-center">
                          {ms.isPaid ? (
                            <span
                              className="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold"
                              style={{
                                backgroundColor: SUCCESS_BG,
                                color: SUCCESS,
                              }}
                            >
                              {t('paid', locale)}
                            </span>
                          ) : (
                            <span
                              className="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-semibold"
                              style={{
                                backgroundColor: 'rgba(27,54,93,0.08)',
                                color: TEXT_MID,
                              }}
                            >
                              {t('unpaid', locale)}
                            </span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* ============================================================ */}
          {/* NOTES                                                        */}
          {/* ============================================================ */}
          {invoice.notes && (
            <div className="mb-8">
              <h3
                className="mb-2 text-sm font-semibold uppercase tracking-wider"
                style={{ color: TEXT_MUTED }}
              >
                {t('notes', locale)}
              </h3>
              <div
                className="whitespace-pre-line rounded-lg p-4 text-sm leading-relaxed"
                style={{ backgroundColor: CARD, color: TEXT_MID }}
              >
                {invoice.notes}
              </div>
            </div>
          )}

          {/* ============================================================ */}
          {/* TERMS (COLLAPSIBLE)                                          */}
          {/* ============================================================ */}
          {terms && (
            <div className="mb-8">
              <button
                type="button"
                onClick={() => setTermsOpen(!termsOpen)}
                className="flex w-full items-center justify-between rounded-lg p-4 text-left text-sm font-semibold transition-colors"
                style={{
                  backgroundColor: CARD,
                  color: NAVY,
                }}
              >
                <span className="uppercase tracking-wider">
                  {t('terms', locale)}
                </span>
                <svg
                  className={`h-5 w-5 shrink-0 transition-transform ${termsOpen ? 'rotate-180' : ''}`}
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </button>
              {termsOpen && (
                <div
                  className="mt-2 whitespace-pre-line rounded-lg p-4 text-xs leading-relaxed"
                  style={{ backgroundColor: CARD, color: TEXT_MID }}
                >
                  {terms}
                </div>
              )}
            </div>
          )}

          {/* ============================================================ */}
          {/* APPROVAL BANNER (if already approved)                        */}
          {/* ============================================================ */}
          {(approvalState.approved || invoice.approvedAt) && (
            <div
              className="mb-6 flex items-center gap-3 rounded-xl p-4"
              style={{ backgroundColor: SUCCESS_BG }}
            >
              <svg
                className="h-6 w-6 shrink-0"
                fill="none"
                viewBox="0 0 24 24"
                stroke={SUCCESS}
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <div>
                <p className="font-semibold" style={{ color: SUCCESS }}>
                  {t('approved', locale)}
                </p>
                {invoice.approvedAt && (
                  <p className="text-xs" style={{ color: TEXT_MID }}>
                    {t('approvedOn', locale)}:{' '}
                    {formatDate(invoice.approvedAt, locale)}
                  </p>
                )}
              </div>
            </div>
          )}

          {/* ============================================================ */}
          {/* ACTION BUTTONS                                               */}
          {/* ============================================================ */}
          <div className="flex flex-col gap-3 sm:flex-row sm:justify-end print:hidden">
            {/* Download PDF — uses the API with shareToken lookup */}
            <a
              href={`/api/invoices/${invoice.id}/pdf?download=true`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 rounded-xl border-2 px-6 py-3 text-sm font-semibold transition-colors hover:opacity-80"
              style={{
                borderColor: NAVY,
                color: NAVY,
                backgroundColor: 'transparent',
              }}
            >
              <svg
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
              </svg>
              {t('downloadPdf', locale)}
            </a>

            {/* Approve button */}
            {canApprove && !approvalState.approved && (
              <button
                type="button"
                onClick={handleApprove}
                disabled={isPending}
                className="inline-flex items-center justify-center gap-2 rounded-xl px-8 py-3 text-sm font-bold text-white transition-colors disabled:opacity-60"
                style={{
                  backgroundColor: isPending ? GOLD_HOVER : GOLD,
                }}
              >
                {isPending ? (
                  <>
                    <svg
                      className="h-4 w-4 animate-spin"
                      viewBox="0 0 24 24"
                      fill="none"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                      />
                    </svg>
                    {t('approving', locale)}
                  </>
                ) : (
                  <>
                    <svg
                      className="h-4 w-4"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    {t('approve', locale)}
                  </>
                )}
              </button>
            )}
          </div>

          {/* Error message */}
          {approvalState.error && (
            <div
              className="mt-4 rounded-lg p-3 text-center text-sm"
              style={{ backgroundColor: ERROR_BG, color: ERROR }}
            >
              {approvalState.error}
            </div>
          )}
        </div>

        {/* ============================================================ */}
        {/* FOOTER                                                       */}
        {/* ============================================================ */}
        <footer className="mt-6 text-center text-xs print:mt-4" style={{ color: TEXT_MUTED }}>
          <p>
            {t('generatedBy', locale)} {company.name}
          </p>
          <p className="mt-1">
            {company.phone} &middot; {company.email}
          </p>
        </footer>
      </div>
    </div>
  );
}
