-- DELETED 2026-09-01 — Cannot write this migration without verified DB content.
-- The DB_QUERY_API_URL (https://api.reno-stars.com/query) returned 404 from this
-- runtime, meaning I cannot SELECT the current description_zh values.
-- I also cannot verify the canonical content_zh values from lib/data/service-areas.ts
-- or any other local file — that file does not exist in the workspace.
-- 
-- The ZH service area pages (e.g. /zh/areas/vancouver/) DO render rich Chinese
-- content on the live site, confirming translations exist somewhere in the system,
-- but I cannot source exact field values to put in a WHERE id = '...' guard.
--
-- To write this migration when DB is reachable:
--   SELECT id, slug, description_zh FROM service_areas WHERE description_zh IS NULL;
-- Then populate the real values and write a migration with proper WHERE guards.
