-- Migration: repair machine-translated renovation terms in zh / zh-Hant copy.
--   pnpm db:query -f scripts/migrations/2026-09-24-zh-glossary-terms.sql --dry-run   # then without --dry-run
-- NOT APPLIED to production when authored (2026-09-24). Applying it is a human decision.
--
-- GENERATED by scripts/fix-zh-glossary.ts from a read-only production audit on
-- 2026-09-24; the rules and their rationale are in scripts/lib/zh-glossary.ts.
-- Each UPDATE replaces ONE exact phrase in ONE column (or one localizations
-- ZhHant key) and touches only rows containing it. Statements for a column run
-- in glossary order, most specific phrase first. Idempotent: a second run
-- changes 0 rows.
--
-- Pre-audit: 154 (column, phrase) hits over 809 row-matches;
-- 7 (column, /en/-link) hits over 572 row-matches.
--
-- Pre-check (expect > 0):   SELECT count(*) FROM services
--   WHERE strpos(description_zh, '一支球队') > 0 OR strpos(long_description_zh, 'Building 代码') > 0;
-- Post-check (expect 0):    same query. Then re-run the audit:
--   npx tsx scripts/fix-zh-glossary.ts --audit-sql | psql ... -At -F"|"
--   and expect no 'rule' / 'link' lines.
-- After applying: revalidate the affected pages (POST /api/revalidate) —
-- direct DB edits do not trigger on-demand revalidation.

-- about_sections.localizations->>whyChooseUsZhHant
UPDATE about_sections SET localizations = jsonb_set(localizations, ARRAY['whyChooseUsZhHant'], to_jsonb(replace((localizations->>'whyChooseUsZhHant'), '美元', '加元'))) WHERE strpos((localizations->>'whyChooseUsZhHant'), '美元') > 0;
-- blog_posts.content_zh
UPDATE blog_posts SET content_zh = replace(content_zh, '聚星裝修', '聚星装修') WHERE strpos(content_zh, '聚星裝修') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆空气', '补风') WHERE strpos(content_zh, '化妆空气') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆品翻新', '表面翻新') WHERE strpos(content_zh, '化妆品翻新') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆品更新', '表面更新') WHERE strpos(content_zh, '化妆品更新') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆品刷新', '表面焕新') WHERE strpos(content_zh, '化妆品刷新') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆品级别', '外观层面') WHERE strpos(content_zh, '化妆品级别') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '化妆品交换', '表面更换') WHERE strpos(content_zh, '化妆品交换') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, 'BC Building 代码', 'BC省建筑规范') WHERE strpos(content_zh, 'BC Building 代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, 'Building 代码', '建筑规范') WHERE strpos(content_zh, 'Building 代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '能源步骤代码', '能源阶梯规范') WHERE strpos(content_zh, '能源步骤代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '能源步进代码', '能源阶梯规范') WHERE strpos(content_zh, '能源步进代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '能源阶梯代码', '能源阶梯规范') WHERE strpos(content_zh, '能源阶梯代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '步骤代码', '阶梯规范') WHERE strpos(content_zh, '步骤代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, 'BC 代码', 'BC 规范') WHERE strpos(content_zh, 'BC 代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '有代码支持，非吸力', '符合规范的固定安装，非吸盘式') WHERE strpos(content_zh, '有代码支持，非吸力') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '一套完整的代码支持', '一套完整、符合规范的') WHERE strpos(content_zh, '一套完整的代码支持') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '完整代码升级', '全面按规范升级') WHERE strpos(content_zh, '完整代码升级') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '完全代码分离', '完全按规范分隔') WHERE strpos(content_zh, '完全代码分离') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '成为代码触发器', '触发规范要求') WHERE strpos(content_zh, '成为代码触发器') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '最昂贵的代码工作', '最昂贵的规范相关工程') WHERE strpos(content_zh, '最昂贵的代码工作') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '按代码', '按规范') WHERE strpos(content_zh, '按代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '代码要求', '规范要求') WHERE strpos(content_zh, '代码要求') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '代码升级', '规范升级') WHERE strpos(content_zh, '代码升级') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '最低代码', '最低规范') WHERE strpos(content_zh, '最低代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '当前代码', '现行规范') WHERE strpos(content_zh, '当前代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '且代码可接受', '且符合规范') WHERE strpos(content_zh, '且代码可接受') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '许可证和代码', '许可证和规范') WHERE strpos(content_zh, '许可证和代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '保险和代码', '保险和规范') WHERE strpos(content_zh, '保险和代码') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '美元数字', '具体金额') WHERE strpos(content_zh, '美元数字') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '美元金额', '金额') WHERE strpos(content_zh, '美元金额') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '美元', '加元') WHERE strpos(content_zh, '美元') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '美金', '加元') WHERE strpos(content_zh, '美金') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '虚荣心', '浴室柜') WHERE strpos(content_zh, '虚荣心') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '虚荣', '浴室柜') WHERE strpos(content_zh, '虚荣') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '梳妆台', '浴室柜') WHERE strpos(content_zh, '梳妆台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '回扣', '补贴') WHERE strpos(content_zh, '回扣') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '贸易许可证', '各工种许可证') WHERE strpos(content_zh, '贸易许可证') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '贸易', '工种') WHERE strpos(content_zh, '贸易') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '测量粗加工', '测量坑距') WHERE strpos(content_zh, '测量粗加工') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '粗加工', '预埋') WHERE strpos(content_zh, '粗加工') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '甲板', '木平台') WHERE strpos(content_zh, '甲板') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '绘画、修剪、', '油漆、收边、') WHERE strpos(content_zh, '绘画、修剪、') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '油漆、修剪和精加工', '油漆、收边和收尾') WHERE strpos(content_zh, '油漆、修剪和精加工') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '绘画', '油漆') WHERE strpos(content_zh, '绘画') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '内阁重铺', '橱柜翻新') WHERE strpos(content_zh, '内阁重铺') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '内阁', '橱柜') WHERE strpos(content_zh, '内阁') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '石英柜台', '石英台面') WHERE strpos(content_zh, '石英柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台面积', '台面面积') WHERE strpos(content_zh, '柜台面积') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台平方英尺', '台面平方英尺') WHERE strpos(content_zh, '柜台平方英尺') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台必须取下来', '台面必须取下来') WHERE strpos(content_zh, '柜台必须取下来') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '浴室柜+柜台', '浴室柜+台面') WHERE strpos(content_zh, '浴室柜+柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '橱柜+柜台', '橱柜+台面') WHERE strpos(content_zh, '橱柜+柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '水槽/柜台', '水槽/台面') WHERE strpos(content_zh, '水槽/柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '降低柜台', '降低台面') WHERE strpos(content_zh, '降低柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '低矮柜台', '低矮台面') WHERE strpos(content_zh, '低矮柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '较低的柜台', '较低的台面') WHERE strpos(content_zh, '较低的柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台高度', '台面高度') WHERE strpos(content_zh, '柜台高度') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台边缘', '台面边缘') WHERE strpos(content_zh, '柜台边缘') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台交换', '台面更换') WHERE strpos(content_zh, '柜台交换') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台更换', '台面更换') WHERE strpos(content_zh, '柜台更换') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台插座', '台面插座') WHERE strpos(content_zh, '柜台插座') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台之间', '台面之间') WHERE strpos(content_zh, '柜台之间') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台下方', '台面下方') WHERE strpos(content_zh, '柜台下方') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '至柜台', '至台面') WHERE strpos(content_zh, '至柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '新柜台', '新台面') WHERE strpos(content_zh, '新柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '着陆柜台', '预留台面') WHERE strpos(content_zh, '着陆柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '柜台岛', '中岛台面') WHERE strpos(content_zh, '柜台岛') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '移过柜台', '移过台面') WHERE strpos(content_zh, '移过柜台') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '在柜台中', '在台面中') WHERE strpos(content_zh, '在柜台中') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '入口处设有酒吧', '入口处设有扶手') WHERE strpos(content_zh, '入口处设有酒吧') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '酒吧拉手', '条形拉手') WHERE strpos(content_zh, '酒吧拉手') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '（英文）</a>', '</a>') WHERE strpos(content_zh, '（英文）</a>') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '更换化妆品柜', '原位更换橱柜') WHERE strpos(content_zh, '更换化妆品柜') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, '橱柜里诺', '橱柜翻新') WHERE strpos(content_zh, '橱柜里诺') > 0;
-- blog_posts.excerpt_zh
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '聚星裝修', '聚星装修') WHERE strpos(excerpt_zh, '聚星裝修') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '化妆品更新', '表面更新') WHERE strpos(excerpt_zh, '化妆品更新') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, 'BC Building 代码', 'BC省建筑规范') WHERE strpos(excerpt_zh, 'BC Building 代码') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, 'Building 代码', '建筑规范') WHERE strpos(excerpt_zh, 'Building 代码') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '美元', '加元') WHERE strpos(excerpt_zh, '美元') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '梳妆台', '浴室柜') WHERE strpos(excerpt_zh, '梳妆台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '回扣', '补贴') WHERE strpos(excerpt_zh, '回扣') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '甲板', '木平台') WHERE strpos(excerpt_zh, '甲板') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台面积', '台面面积') WHERE strpos(excerpt_zh, '柜台面积') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台平方英尺', '台面平方英尺') WHERE strpos(excerpt_zh, '柜台平方英尺') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台必须取下来', '台面必须取下来') WHERE strpos(excerpt_zh, '柜台必须取下来') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '浴室柜+柜台', '浴室柜+台面') WHERE strpos(excerpt_zh, '浴室柜+柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '橱柜+柜台', '橱柜+台面') WHERE strpos(excerpt_zh, '橱柜+柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '水槽/柜台', '水槽/台面') WHERE strpos(excerpt_zh, '水槽/柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '降低柜台', '降低台面') WHERE strpos(excerpt_zh, '降低柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '低矮柜台', '低矮台面') WHERE strpos(excerpt_zh, '低矮柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '较低的柜台', '较低的台面') WHERE strpos(excerpt_zh, '较低的柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台高度', '台面高度') WHERE strpos(excerpt_zh, '柜台高度') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台边缘', '台面边缘') WHERE strpos(excerpt_zh, '柜台边缘') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台交换', '台面更换') WHERE strpos(excerpt_zh, '柜台交换') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台更换', '台面更换') WHERE strpos(excerpt_zh, '柜台更换') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台插座', '台面插座') WHERE strpos(excerpt_zh, '柜台插座') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台之间', '台面之间') WHERE strpos(excerpt_zh, '柜台之间') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台下方', '台面下方') WHERE strpos(excerpt_zh, '柜台下方') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '至柜台', '至台面') WHERE strpos(excerpt_zh, '至柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '新柜台', '新台面') WHERE strpos(excerpt_zh, '新柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '着陆柜台', '预留台面') WHERE strpos(excerpt_zh, '着陆柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '柜台岛', '中岛台面') WHERE strpos(excerpt_zh, '柜台岛') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '移过柜台', '移过台面') WHERE strpos(excerpt_zh, '移过柜台') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '在柜台中', '在台面中') WHERE strpos(excerpt_zh, '在柜台中') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '更换化妆品柜', '原位更换橱柜') WHERE strpos(excerpt_zh, '更换化妆品柜') > 0;
UPDATE blog_posts SET excerpt_zh = replace(excerpt_zh, '橱柜里诺', '橱柜翻新') WHERE strpos(excerpt_zh, '橱柜里诺') > 0;
-- blog_posts.focus_keyword_zh
UPDATE blog_posts SET focus_keyword_zh = replace(focus_keyword_zh, '聚星裝修', '聚星装修') WHERE strpos(focus_keyword_zh, '聚星裝修') > 0;
-- blog_posts.localizations->>contentZhHant
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝空氣', '補風'))) WHERE strpos((localizations->>'contentZhHant'), '化妝空氣') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝品翻新', '表面翻新'))) WHERE strpos((localizations->>'contentZhHant'), '化妝品翻新') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝品更新', '表面更新'))) WHERE strpos((localizations->>'contentZhHant'), '化妝品更新') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝品刷新', '表面煥新'))) WHERE strpos((localizations->>'contentZhHant'), '化妝品刷新') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝品裝修', '表面裝修'))) WHERE strpos((localizations->>'contentZhHant'), '化妝品裝修') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '管道代碼', '管道規範'))) WHERE strpos((localizations->>'contentZhHant'), '管道代碼') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), 'BC 代碼', 'BC 規範'))) WHERE strpos((localizations->>'contentZhHant'), 'BC 代碼') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '代碼要求', '規範要求'))) WHERE strpos((localizations->>'contentZhHant'), '代碼要求') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '代碼驚喜', '規範意外'))) WHERE strpos((localizations->>'contentZhHant'), '代碼驚喜') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '代碼合規性', '規範合規性'))) WHERE strpos((localizations->>'contentZhHant'), '代碼合規性') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '目前代碼', '現行規範'))) WHERE strpos((localizations->>'contentZhHant'), '目前代碼') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '美元範圍', '預算範圍'))) WHERE strpos((localizations->>'contentZhHant'), '美元範圍') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '美元', '加元'))) WHERE strpos((localizations->>'contentZhHant'), '美元') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '虛榮心', '浴室櫃'))) WHERE strpos((localizations->>'contentZhHant'), '虛榮心') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '虛榮', '浴室櫃'))) WHERE strpos((localizations->>'contentZhHant'), '虛榮') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '梳妆台', '浴室櫃'))) WHERE strpos((localizations->>'contentZhHant'), '梳妆台') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'contentZhHant'), '回扣') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '貿易', '工種'))) WHERE strpos((localizations->>'contentZhHant'), '貿易') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '測量粗加工', '測量坑距'))) WHERE strpos((localizations->>'contentZhHant'), '測量粗加工') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '粗加工', '預埋'))) WHERE strpos((localizations->>'contentZhHant'), '粗加工') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '甲板', '木平台'))) WHERE strpos((localizations->>'contentZhHant'), '甲板') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '繪畫', '油漆'))) WHERE strpos((localizations->>'contentZhHant'), '繪畫') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '绘画', '油漆'))) WHERE strpos((localizations->>'contentZhHant'), '绘画') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '內閣', '櫥櫃'))) WHERE strpos((localizations->>'contentZhHant'), '內閣') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '石櫃檯', '石材檯面'))) WHERE strpos((localizations->>'contentZhHant'), '石櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯層級', '檯面等級'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯層級') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯翻新', '檯面翻新'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯翻新') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '層壓板櫃檯', '層壓板檯面'))) WHERE strpos((localizations->>'contentZhHant'), '層壓板櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '安裝櫃檯', '安裝檯面'))) WHERE strpos((localizations->>'contentZhHant'), '安裝櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯高度', '檯面高度'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯高度') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '移過櫃檯', '移過檯面'))) WHERE strpos((localizations->>'contentZhHant'), '移過櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫥櫃裡諾', '櫥櫃翻新'))) WHERE strpos((localizations->>'contentZhHant'), '櫥櫃裡諾') > 0;
-- blog_posts.localizations->>excerptZhHant
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['excerptZhHant'], to_jsonb(replace((localizations->>'excerptZhHant'), '美元', '加元'))) WHERE strpos((localizations->>'excerptZhHant'), '美元') > 0;
-- blog_posts.localizations->>metaDescriptionZhHant
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), 'BC 代碼', 'BC 規範'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), 'BC 代碼') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), 'BC代碼', 'BC規範'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), 'BC代碼') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '梳妆台', '浴室櫃'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '梳妆台') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '回扣') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '櫃檯層級', '檯面等級'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '櫃檯層級') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '櫃檯翻新', '檯面翻新'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '櫃檯翻新') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '層壓板櫃檯', '層壓板檯面'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '層壓板櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '安裝櫃檯', '安裝檯面'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '安裝櫃檯') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '櫃檯高度', '檯面高度'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '櫃檯高度') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '移過櫃檯', '移過檯面'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '移過櫃檯') > 0;
-- blog_posts.localizations->>metaTitleZhHant
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['metaTitleZhHant'], to_jsonb(replace((localizations->>'metaTitleZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'metaTitleZhHant'), '回扣') > 0;
-- blog_posts.localizations->>titleZhHant
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['titleZhHant'], to_jsonb(replace((localizations->>'titleZhHant'), '甲板', '木平台'))) WHERE strpos((localizations->>'titleZhHant'), '甲板') > 0;
-- blog_posts.meta_description_zh
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '聚星裝修', '聚星装修') WHERE strpos(meta_description_zh, '聚星裝修') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, 'BC 代码', 'BC 规范') WHERE strpos(meta_description_zh, 'BC 代码') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '梳妆台', '浴室柜') WHERE strpos(meta_description_zh, '梳妆台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '回扣', '补贴') WHERE strpos(meta_description_zh, '回扣') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '甲板', '木平台') WHERE strpos(meta_description_zh, '甲板') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台面积', '台面面积') WHERE strpos(meta_description_zh, '柜台面积') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台平方英尺', '台面平方英尺') WHERE strpos(meta_description_zh, '柜台平方英尺') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台必须取下来', '台面必须取下来') WHERE strpos(meta_description_zh, '柜台必须取下来') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '浴室柜+柜台', '浴室柜+台面') WHERE strpos(meta_description_zh, '浴室柜+柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '橱柜+柜台', '橱柜+台面') WHERE strpos(meta_description_zh, '橱柜+柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '水槽/柜台', '水槽/台面') WHERE strpos(meta_description_zh, '水槽/柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '降低柜台', '降低台面') WHERE strpos(meta_description_zh, '降低柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '低矮柜台', '低矮台面') WHERE strpos(meta_description_zh, '低矮柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '较低的柜台', '较低的台面') WHERE strpos(meta_description_zh, '较低的柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台高度', '台面高度') WHERE strpos(meta_description_zh, '柜台高度') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台边缘', '台面边缘') WHERE strpos(meta_description_zh, '柜台边缘') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台交换', '台面更换') WHERE strpos(meta_description_zh, '柜台交换') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台更换', '台面更换') WHERE strpos(meta_description_zh, '柜台更换') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台插座', '台面插座') WHERE strpos(meta_description_zh, '柜台插座') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台之间', '台面之间') WHERE strpos(meta_description_zh, '柜台之间') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台下方', '台面下方') WHERE strpos(meta_description_zh, '柜台下方') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '至柜台', '至台面') WHERE strpos(meta_description_zh, '至柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '新柜台', '新台面') WHERE strpos(meta_description_zh, '新柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '着陆柜台', '预留台面') WHERE strpos(meta_description_zh, '着陆柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '柜台岛', '中岛台面') WHERE strpos(meta_description_zh, '柜台岛') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '移过柜台', '移过台面') WHERE strpos(meta_description_zh, '移过柜台') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '在柜台中', '在台面中') WHERE strpos(meta_description_zh, '在柜台中') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '更换化妆品柜', '原位更换橱柜') WHERE strpos(meta_description_zh, '更换化妆品柜') > 0;
UPDATE blog_posts SET meta_description_zh = replace(meta_description_zh, '橱柜里诺', '橱柜翻新') WHERE strpos(meta_description_zh, '橱柜里诺') > 0;
-- blog_posts.meta_title_zh
UPDATE blog_posts SET meta_title_zh = replace(meta_title_zh, '聚星裝修', '聚星装修') WHERE strpos(meta_title_zh, '聚星裝修') > 0;
UPDATE blog_posts SET meta_title_zh = replace(meta_title_zh, '甲板', '木平台') WHERE strpos(meta_title_zh, '甲板') > 0;
-- blog_posts.seo_keywords_zh
UPDATE blog_posts SET seo_keywords_zh = replace(seo_keywords_zh, '聚星裝修', '聚星装修') WHERE strpos(seo_keywords_zh, '聚星裝修') > 0;
UPDATE blog_posts SET seo_keywords_zh = replace(seo_keywords_zh, '回扣', '补贴') WHERE strpos(seo_keywords_zh, '回扣') > 0;
UPDATE blog_posts SET seo_keywords_zh = replace(seo_keywords_zh, '甲板', '木平台') WHERE strpos(seo_keywords_zh, '甲板') > 0;
-- blog_posts.title_zh
UPDATE blog_posts SET title_zh = replace(title_zh, '聚星裝修', '聚星装修') WHERE strpos(title_zh, '聚星裝修') > 0;
UPDATE blog_posts SET title_zh = replace(title_zh, '甲板', '木平台') WHERE strpos(title_zh, '甲板') > 0;
-- faqs.answer_zh
UPDATE faqs SET answer_zh = replace(answer_zh, '美元', '加元') WHERE strpos(answer_zh, '美元') > 0;
-- faqs.localizations->>answerZhHant
UPDATE faqs SET localizations = jsonb_set(localizations, ARRAY['answerZhHant'], to_jsonb(replace((localizations->>'answerZhHant'), '美元', '加元'))) WHERE strpos((localizations->>'answerZhHant'), '美元') > 0;
-- projects.description_zh
UPDATE projects SET description_zh = replace(description_zh, '美元', '加元') WHERE strpos(description_zh, '美元') > 0;
-- projects.localizations->>metaDescriptionZhHant
UPDATE projects SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '貿易', '工種'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '貿易') > 0;
UPDATE projects SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '測量粗加工', '測量坑距'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '測量粗加工') > 0;
UPDATE projects SET localizations = jsonb_set(localizations, ARRAY['metaDescriptionZhHant'], to_jsonb(replace((localizations->>'metaDescriptionZhHant'), '粗加工', '預埋'))) WHERE strpos((localizations->>'metaDescriptionZhHant'), '粗加工') > 0;
-- projects.meta_description_zh
UPDATE projects SET meta_description_zh = replace(meta_description_zh, '贸易', '工种') WHERE strpos(meta_description_zh, '贸易') > 0;
UPDATE projects SET meta_description_zh = replace(meta_description_zh, '测量粗加工', '测量坑距') WHERE strpos(meta_description_zh, '测量粗加工') > 0;
UPDATE projects SET meta_description_zh = replace(meta_description_zh, '粗加工', '预埋') WHERE strpos(meta_description_zh, '粗加工') > 0;
UPDATE projects SET meta_description_zh = replace(meta_description_zh, '油漆、修剪和精加工', '油漆、收边和收尾') WHERE strpos(meta_description_zh, '油漆、修剪和精加工') > 0;
-- service_areas.content_zh
UPDATE service_areas SET content_zh = replace(content_zh, '化妆品更新', '表面更新') WHERE strpos(content_zh, '化妆品更新') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '回扣', '补贴') WHERE strpos(content_zh, '回扣') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '贸易', '工种') WHERE strpos(content_zh, '贸易') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '测量粗加工', '测量坑距') WHERE strpos(content_zh, '测量粗加工') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '粗加工', '预埋') WHERE strpos(content_zh, '粗加工') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '甲板', '木平台') WHERE strpos(content_zh, '甲板') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '油漆、修剪和精加工', '油漆、收边和收尾') WHERE strpos(content_zh, '油漆、修剪和精加工') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '内阁重铺', '橱柜翻新') WHERE strpos(content_zh, '内阁重铺') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '内阁', '橱柜') WHERE strpos(content_zh, '内阁') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台面积', '台面面积') WHERE strpos(content_zh, '柜台面积') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台平方英尺', '台面平方英尺') WHERE strpos(content_zh, '柜台平方英尺') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台必须取下来', '台面必须取下来') WHERE strpos(content_zh, '柜台必须取下来') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '浴室柜+柜台', '浴室柜+台面') WHERE strpos(content_zh, '浴室柜+柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '橱柜+柜台', '橱柜+台面') WHERE strpos(content_zh, '橱柜+柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '水槽/柜台', '水槽/台面') WHERE strpos(content_zh, '水槽/柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '降低柜台', '降低台面') WHERE strpos(content_zh, '降低柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '低矮柜台', '低矮台面') WHERE strpos(content_zh, '低矮柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '较低的柜台', '较低的台面') WHERE strpos(content_zh, '较低的柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台高度', '台面高度') WHERE strpos(content_zh, '柜台高度') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台边缘', '台面边缘') WHERE strpos(content_zh, '柜台边缘') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台交换', '台面更换') WHERE strpos(content_zh, '柜台交换') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台更换', '台面更换') WHERE strpos(content_zh, '柜台更换') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台插座', '台面插座') WHERE strpos(content_zh, '柜台插座') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台之间', '台面之间') WHERE strpos(content_zh, '柜台之间') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台下方', '台面下方') WHERE strpos(content_zh, '柜台下方') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '至柜台', '至台面') WHERE strpos(content_zh, '至柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '新柜台', '新台面') WHERE strpos(content_zh, '新柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '着陆柜台', '预留台面') WHERE strpos(content_zh, '着陆柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '柜台岛', '中岛台面') WHERE strpos(content_zh, '柜台岛') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '移过柜台', '移过台面') WHERE strpos(content_zh, '移过柜台') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '在柜台中', '在台面中') WHERE strpos(content_zh, '在柜台中') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '更换化妆品柜', '原位更换橱柜') WHERE strpos(content_zh, '更换化妆品柜') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '橱柜里诺', '橱柜翻新') WHERE strpos(content_zh, '橱柜里诺') > 0;
-- service_areas.localizations->>contentZhHant
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '化妝品更新', '表面更新'))) WHERE strpos((localizations->>'contentZhHant'), '化妝品更新') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'contentZhHant'), '回扣') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '貿易', '工種'))) WHERE strpos((localizations->>'contentZhHant'), '貿易') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '測量粗加工', '測量坑距'))) WHERE strpos((localizations->>'contentZhHant'), '測量粗加工') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '粗加工', '預埋'))) WHERE strpos((localizations->>'contentZhHant'), '粗加工') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '甲板', '木平台'))) WHERE strpos((localizations->>'contentZhHant'), '甲板') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '內閣', '櫥櫃'))) WHERE strpos((localizations->>'contentZhHant'), '內閣') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯層級', '檯面等級'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯層級') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯翻新', '檯面翻新'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯翻新') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '層壓板櫃檯', '層壓板檯面'))) WHERE strpos((localizations->>'contentZhHant'), '層壓板櫃檯') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '安裝櫃檯', '安裝檯面'))) WHERE strpos((localizations->>'contentZhHant'), '安裝櫃檯') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫃檯高度', '檯面高度'))) WHERE strpos((localizations->>'contentZhHant'), '櫃檯高度') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '移過櫃檯', '移過檯面'))) WHERE strpos((localizations->>'contentZhHant'), '移過櫃檯') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '櫥櫃裡諾', '櫥櫃翻新'))) WHERE strpos((localizations->>'contentZhHant'), '櫥櫃裡諾') > 0;
-- service_benefits.localizations->>benefitZhHant
UPDATE service_benefits SET localizations = jsonb_set(localizations, ARRAY['benefitZhHant'], to_jsonb(replace((localizations->>'benefitZhHant'), '美元', '加元'))) WHERE strpos((localizations->>'benefitZhHant'), '美元') > 0;
UPDATE service_benefits SET localizations = jsonb_set(localizations, ARRAY['benefitZhHant'], to_jsonb(replace((localizations->>'benefitZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'benefitZhHant'), '回扣') > 0;
-- service_tags.localizations->>tagZhHant
UPDATE service_tags SET localizations = jsonb_set(localizations, ARRAY['tagZhHant'], to_jsonb(replace((localizations->>'tagZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'tagZhHant'), '回扣') > 0;
-- services.description_zh
UPDATE services SET description_zh = replace(description_zh, '一支球队', '一个团队') WHERE strpos(description_zh, '一支球队') > 0;
-- services.localizations->>descriptionZhHant
UPDATE services SET localizations = jsonb_set(localizations, ARRAY['descriptionZhHant'], to_jsonb(replace((localizations->>'descriptionZhHant'), '一支球隊', '一個團隊'))) WHERE strpos((localizations->>'descriptionZhHant'), '一支球隊') > 0;
UPDATE services SET localizations = jsonb_set(localizations, ARRAY['descriptionZhHant'], to_jsonb(replace((localizations->>'descriptionZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'descriptionZhHant'), '回扣') > 0;
-- services.localizations->>longDescriptionZhHant
UPDATE services SET localizations = jsonb_set(localizations, ARRAY['longDescriptionZhHant'], to_jsonb(replace((localizations->>'longDescriptionZhHant'), '回扣', '補貼'))) WHERE strpos((localizations->>'longDescriptionZhHant'), '回扣') > 0;
-- services.long_description_zh
UPDATE services SET long_description_zh = replace(long_description_zh, '化妆品刷新', '表面焕新') WHERE strpos(long_description_zh, '化妆品刷新') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, 'BC Building 代码', 'BC省建筑规范') WHERE strpos(long_description_zh, 'BC Building 代码') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, 'Building 代码', '建筑规范') WHERE strpos(long_description_zh, 'Building 代码') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '管道代码', '管道规范') WHERE strpos(long_description_zh, '管道代码') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '代码审查', '规范审查') WHERE strpos(long_description_zh, '代码审查') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '关键代码项', '关键规范项') WHERE strpos(long_description_zh, '关键代码项') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '虚荣', '浴室柜') WHERE strpos(long_description_zh, '虚荣') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '贸易', '工种') WHERE strpos(long_description_zh, '贸易') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '测量粗加工', '测量坑距') WHERE strpos(long_description_zh, '测量粗加工') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '粗加工', '预埋') WHERE strpos(long_description_zh, '粗加工') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '油漆、修剪和精加工', '油漆、收边和收尾') WHERE strpos(long_description_zh, '油漆、修剪和精加工') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '石英柜台', '石英台面') WHERE strpos(long_description_zh, '石英柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台面积', '台面面积') WHERE strpos(long_description_zh, '柜台面积') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台平方英尺', '台面平方英尺') WHERE strpos(long_description_zh, '柜台平方英尺') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台必须取下来', '台面必须取下来') WHERE strpos(long_description_zh, '柜台必须取下来') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '浴室柜+柜台', '浴室柜+台面') WHERE strpos(long_description_zh, '浴室柜+柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '橱柜+柜台', '橱柜+台面') WHERE strpos(long_description_zh, '橱柜+柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '水槽/柜台', '水槽/台面') WHERE strpos(long_description_zh, '水槽/柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '降低柜台', '降低台面') WHERE strpos(long_description_zh, '降低柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '低矮柜台', '低矮台面') WHERE strpos(long_description_zh, '低矮柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '较低的柜台', '较低的台面') WHERE strpos(long_description_zh, '较低的柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台高度', '台面高度') WHERE strpos(long_description_zh, '柜台高度') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台边缘', '台面边缘') WHERE strpos(long_description_zh, '柜台边缘') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台交换', '台面更换') WHERE strpos(long_description_zh, '柜台交换') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台更换', '台面更换') WHERE strpos(long_description_zh, '柜台更换') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台插座', '台面插座') WHERE strpos(long_description_zh, '柜台插座') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台之间', '台面之间') WHERE strpos(long_description_zh, '柜台之间') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台下方', '台面下方') WHERE strpos(long_description_zh, '柜台下方') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '至柜台', '至台面') WHERE strpos(long_description_zh, '至柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '新柜台', '新台面') WHERE strpos(long_description_zh, '新柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '着陆柜台', '预留台面') WHERE strpos(long_description_zh, '着陆柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '柜台岛', '中岛台面') WHERE strpos(long_description_zh, '柜台岛') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '移过柜台', '移过台面') WHERE strpos(long_description_zh, '移过柜台') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '在柜台中', '在台面中') WHERE strpos(long_description_zh, '在柜台中') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '更换化妆品柜', '原位更换橱柜') WHERE strpos(long_description_zh, '更换化妆品柜') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '橱柜里诺', '橱柜翻新') WHERE strpos(long_description_zh, '橱柜里诺') > 0;

-- Chinese copy linking to the English page → same page in this locale
UPDATE blog_posts SET content_zh = replace(content_zh, '](/en/', '](/zh/') WHERE strpos(content_zh, '](/en/') > 0;
UPDATE blog_posts SET content_zh = replace(content_zh, 'href="/en/', 'href="/zh/') WHERE strpos(content_zh, 'href="/en/') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '](/en/', '](/zh-Hant/'))) WHERE strpos((localizations->>'contentZhHant'), '](/en/') > 0;
UPDATE blog_posts SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), 'href="/en/', 'href="/zh-Hant/'))) WHERE strpos((localizations->>'contentZhHant'), 'href="/en/') > 0;
UPDATE service_areas SET content_zh = replace(content_zh, '](/en/', '](/zh/') WHERE strpos(content_zh, '](/en/') > 0;
UPDATE service_areas SET localizations = jsonb_set(localizations, ARRAY['contentZhHant'], to_jsonb(replace((localizations->>'contentZhHant'), '](/en/', '](/zh-Hant/'))) WHERE strpos((localizations->>'contentZhHant'), '](/en/') > 0;
UPDATE services SET long_description_zh = replace(long_description_zh, '](/en/', '](/zh/') WHERE strpos(long_description_zh, '](/en/') > 0;
