'use client';

import { GOLD } from '@/lib/theme';
import {
  excerptTextareaStyle,
  sectionLabelStyle,
  fieldLabelStyle,
} from './styles';

interface ExcerptSectionProps {
  label: string;
  autoGeneratedLabel: string;
  excerptEn: string;
  excerptZh: string;
  onExcerptEnChange: (value: string) => void;
  onExcerptZhChange: (value: string) => void;
  disabled: boolean;
}

export default function ExcerptSection({
  label,
  autoGeneratedLabel,
  excerptEn,
  excerptZh,
  onExcerptEnChange,
  onExcerptZhChange,
  disabled,
}: ExcerptSectionProps) {
  const hasData = excerptEn || excerptZh;

  return (
    <div style={{ marginTop: '1rem' }}>
      <div style={sectionLabelStyle}>
        <span>{label}</span>
        {hasData && (
          <span
            style={{
              fontSize: '0.625rem',
              color: GOLD,
              background: 'rgba(200,146,42,0.1)',
              padding: '0.125rem 0.375rem',
              borderRadius: '4px',
            }}
          >
            {autoGeneratedLabel}
          </span>
        )}
      </div>
      <div className="admin-form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem' }}>
        <div>
          <label style={fieldLabelStyle}>
            <span role="img" aria-label="English">🇺🇸</span> EN
          </label>
          <textarea
            value={excerptEn}
            onChange={(e) => onExcerptEnChange(e.target.value)}
            aria-label="English excerpt"
            rows={2}
            style={{ ...excerptTextareaStyle, opacity: disabled ? 0.6 : 1 }}
            disabled={disabled}
          />
        </div>
        <div>
          <label style={fieldLabelStyle}>
            <span role="img" aria-label="Chinese">🇨🇳</span> ZH
          </label>
          <textarea
            value={excerptZh}
            onChange={(e) => onExcerptZhChange(e.target.value)}
            aria-label="Chinese excerpt"
            rows={2}
            style={{ ...excerptTextareaStyle, opacity: disabled ? 0.6 : 1 }}
            disabled={disabled}
          />
        </div>
      </div>
    </div>
  );
}
