'use client';

import { GOLD, SURFACE } from '@/lib/theme';
import Tooltip from '../Tooltip';
import { inputStyle } from '../shared-styles';
import {
  excerptTextareaStyle,
  sectionLabelStyle,
  fieldLabelStyle,
} from './styles';

const seoInputStyle = {
  ...inputStyle,
  background: SURFACE,
};

interface SEOFieldsSectionProps {
  // Translations
  seoSettingsLabel: string;
  seoTooltip: string;
  autoGeneratedLabel: string;
  metaTitleLabel: string;
  metaDescriptionLabel: string;
  focusKeywordLabel: string;
  seoKeywordsLabel: string;
  // Values
  metaTitleEn: string;
  metaTitleZh: string;
  metaDescriptionEn: string;
  metaDescriptionZh: string;
  focusKeywordEn: string;
  focusKeywordZh: string;
  seoKeywordsEn: string;
  seoKeywordsZh: string;
  // Setters
  onMetaTitleEnChange: (value: string) => void;
  onMetaTitleZhChange: (value: string) => void;
  onMetaDescriptionEnChange: (value: string) => void;
  onMetaDescriptionZhChange: (value: string) => void;
  onFocusKeywordEnChange: (value: string) => void;
  onFocusKeywordZhChange: (value: string) => void;
  onSeoKeywordsEnChange: (value: string) => void;
  onSeoKeywordsZhChange: (value: string) => void;
  disabled: boolean;
}

export default function SEOFieldsSection({
  seoSettingsLabel,
  seoTooltip,
  autoGeneratedLabel,
  metaTitleLabel,
  metaDescriptionLabel,
  focusKeywordLabel,
  seoKeywordsLabel,
  metaTitleEn,
  metaTitleZh,
  metaDescriptionEn,
  metaDescriptionZh,
  focusKeywordEn,
  focusKeywordZh,
  seoKeywordsEn,
  seoKeywordsZh,
  onMetaTitleEnChange,
  onMetaTitleZhChange,
  onMetaDescriptionEnChange,
  onMetaDescriptionZhChange,
  onFocusKeywordEnChange,
  onFocusKeywordZhChange,
  onSeoKeywordsEnChange,
  onSeoKeywordsZhChange,
  disabled,
}: SEOFieldsSectionProps) {
  // Check if any SEO field has data (expanded check)
  const hasSeoData =
    metaTitleEn ||
    metaTitleZh ||
    metaDescriptionEn ||
    metaDescriptionZh ||
    focusKeywordEn ||
    focusKeywordZh ||
    seoKeywordsEn ||
    seoKeywordsZh;

  return (
    <div style={{ marginTop: '1.5rem' }}>
      <div style={sectionLabelStyle}>
        <span>{seoSettingsLabel}</span>
        <Tooltip content={seoTooltip} />
        {hasSeoData && (
          <span
            style={{
              fontSize: '0.625rem',
              color: GOLD,
              background: 'rgba(200,146,42,0.1)',
              padding: '0.125rem 0.375rem',
              borderRadius: '4px',
            }}
          >
            {autoGeneratedLabel}
          </span>
        )}
      </div>

      {/* Meta Titles */}
      <div style={{ marginBottom: '0.75rem' }}>
        <label style={{ ...fieldLabelStyle, marginBottom: '0.375rem' }}>{metaTitleLabel}</label>
        <div className="admin-form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem' }}>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="English">🇺🇸</span> EN ({metaTitleEn.length}/70)
            </label>
            <input
              type="text"
              value={metaTitleEn}
              onChange={(e) => onMetaTitleEnChange(e.target.value)}
              aria-label="English meta title"
              maxLength={70}
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="Chinese">🇨🇳</span> ZH ({metaTitleZh.length}/70)
            </label>
            <input
              type="text"
              value={metaTitleZh}
              onChange={(e) => onMetaTitleZhChange(e.target.value)}
              aria-label="Chinese meta title"
              maxLength={70}
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
        </div>
      </div>

      {/* Meta Descriptions */}
      <div style={{ marginBottom: '0.75rem' }}>
        <label style={{ ...fieldLabelStyle, marginBottom: '0.375rem' }}>{metaDescriptionLabel}</label>
        <div className="admin-form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem' }}>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="English">🇺🇸</span> EN ({metaDescriptionEn.length}/160)
            </label>
            <textarea
              value={metaDescriptionEn}
              onChange={(e) => onMetaDescriptionEnChange(e.target.value)}
              aria-label="English meta description"
              maxLength={160}
              rows={2}
              style={{ ...excerptTextareaStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="Chinese">🇨🇳</span> ZH ({metaDescriptionZh.length}/160)
            </label>
            <textarea
              value={metaDescriptionZh}
              onChange={(e) => onMetaDescriptionZhChange(e.target.value)}
              aria-label="Chinese meta description"
              maxLength={160}
              rows={2}
              style={{ ...excerptTextareaStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
        </div>
      </div>

      {/* Focus Keywords */}
      <div style={{ marginBottom: '0.75rem' }}>
        <label style={{ ...fieldLabelStyle, marginBottom: '0.375rem' }}>{focusKeywordLabel}</label>
        <div className="admin-form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem' }}>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="English">🇺🇸</span> EN
            </label>
            <input
              type="text"
              value={focusKeywordEn}
              onChange={(e) => onFocusKeywordEnChange(e.target.value)}
              aria-label="English focus keyword"
              maxLength={50}
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="Chinese">🇨🇳</span> ZH
            </label>
            <input
              type="text"
              value={focusKeywordZh}
              onChange={(e) => onFocusKeywordZhChange(e.target.value)}
              aria-label="Chinese focus keyword"
              maxLength={50}
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
        </div>
      </div>

      {/* SEO Keywords */}
      <div>
        <label style={{ ...fieldLabelStyle, marginBottom: '0.375rem' }}>{seoKeywordsLabel}</label>
        <div className="admin-form-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem' }}>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="English">🇺🇸</span> EN
            </label>
            <input
              type="text"
              value={seoKeywordsEn}
              onChange={(e) => onSeoKeywordsEnChange(e.target.value)}
              aria-label="English SEO keywords"
              placeholder="keyword1, keyword2, keyword3"
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
          <div>
            <label style={fieldLabelStyle}>
              <span role="img" aria-label="Chinese">🇨🇳</span> ZH
            </label>
            <input
              type="text"
              value={seoKeywordsZh}
              onChange={(e) => onSeoKeywordsZhChange(e.target.value)}
              aria-label="Chinese SEO keywords"
              placeholder="关键词1, 关键词2, 关键词3"
              style={{ ...seoInputStyle, opacity: disabled ? 0.6 : 1 }}
              disabled={disabled}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
