export interface Project {
  title: string;
  category: string;
  location: string;
  image: string;
  description: string;
  badge?: string;
  gallery: string[];
  budget: string;
  spaceType: string;
  duration: string;
  serviceScope: string[];
  challenge: string;
  solution: string;
}

export const categories = ["All", "Kitchen", "Bathroom", "Whole House", "Commercial"];

const categoriesZh = ["全部", "厨房", "卫浴", "全屋", "商业"];

export const projects: Project[] = [
  {
    title: "Coquitlam - White Shaker Cabinets",
    category: "Kitchen",
    location: "Coquitlam",
    image: "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
    description: "Modern white shaker cabinet installation with premium countertops and backsplash.",
    badge: "New",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
    ],
    budget: "$15,000 - $25,000",
    spaceType: "Residential",
    duration: "3 weeks",
    serviceScope: ["Cabinetry", "Countertops", "Backsplash"],
    challenge: "The existing kitchen had outdated oak cabinets and limited counter space, making the kitchen feel cramped and dark.",
    solution: "We installed bright white shaker cabinets with soft-close hardware, paired with quartz countertops and a modern tile backsplash to open up the space.",
  },
  {
    title: "Richmond Kitchen and Bathroom Remodel",
    category: "Kitchen",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
    description: "Complete kitchen and bathroom transformation with contemporary finishes.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$30,000 - $45,000",
    spaceType: "Condo",
    duration: "5 weeks",
    serviceScope: ["Cabinetry", "Countertops", "Flooring", "Plumbing", "Tile Work"],
    challenge: "A dated condo with separate outdated kitchen and bathroom needing a cohesive modern update within a tight timeline.",
    solution: "We coordinated kitchen and bathroom trades simultaneously, using a unified modern palette with quartz surfaces and contemporary fixtures throughout.",
  },
  {
    title: "Surrey Home Renovation",
    category: "Kitchen",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    description: "Full home renovation including a stunning kitchen redesign.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
    ],
    budget: "$40,000 - $60,000",
    spaceType: "Residential",
    duration: "6 weeks",
    serviceScope: ["Kitchen Design", "Cabinetry", "Countertops", "Flooring", "Painting"],
    challenge: "An aging Surrey home required a complete kitchen overhaul while maintaining the structural integrity and flow of the open-concept living area.",
    solution: "We redesigned the kitchen layout for better workflow, installed custom cabinetry, and chose durable yet stylish materials that complement the open-concept design.",
  },
  {
    title: "White Toned Kitchen in Surrey",
    category: "Kitchen",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
    description: "Elegant white-toned kitchen renovation with clean lines and modern appliances.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
      "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    ],
    budget: "$20,000 - $35,000",
    spaceType: "Residential",
    duration: "4 weeks",
    serviceScope: ["Cabinetry", "Countertops", "Appliance Installation", "Lighting"],
    challenge: "The homeowner wanted a bright, airy kitchen but the existing layout had poor lighting and dark-toned finishes.",
    solution: "We implemented an all-white palette with under-cabinet LED lighting, reflective quartz countertops, and strategically placed pot lights to maximize brightness.",
  },
  {
    title: "Kitchen Renovation in Delta BC",
    category: "Kitchen",
    location: "Delta",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
    description: "Modern kitchen renovation featuring custom cabinetry and quartz countertops.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
    ],
    budget: "$25,000 - $40,000",
    spaceType: "Residential",
    duration: "4 weeks",
    serviceScope: ["Cabinetry", "Countertops", "Backsplash", "Plumbing"],
    challenge: "Limited counter space and outdated appliances made the kitchen inefficient for a family of five.",
    solution: "We reconfigured the layout to include an island with extra storage, installed quartz countertops, and added a modern tile backsplash for a functional family kitchen.",
  },
  {
    title: "Modern Kitchen Renovation in Richmond",
    category: "Kitchen",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
    description: "Comprehensive modern kitchen renovation with island and premium fixtures.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
    ],
    budget: "$35,000 - $50,000",
    spaceType: "Residential",
    duration: "5 weeks",
    serviceScope: ["Kitchen Design", "Cabinetry", "Countertops", "Island", "Fixtures"],
    challenge: "The homeowners wanted a chef-grade kitchen with an island but the existing space had load-bearing walls limiting the layout options.",
    solution: "We worked with a structural engineer to safely open up the space, then installed a large waterfall-edge island, premium cabinetry, and professional-grade fixtures.",
  },
  {
    title: "Bathroom Renovation in Delta",
    category: "Bathroom",
    location: "Delta",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
    description: "Complete bathroom renovation with luxury tile work and modern vanity.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    ],
    budget: "$12,000 - $20,000",
    spaceType: "Residential",
    duration: "2 weeks",
    serviceScope: ["Tile Work", "Vanity", "Plumbing", "Lighting"],
    challenge: "A small bathroom with water damage and an inefficient layout that wasted valuable floor space.",
    solution: "We repaired the water damage, reconfigured the layout for a walk-in shower, and installed large-format tiles and a floating vanity to create a spacious feel.",
  },
  {
    title: "Richmond Bathroom Remodel",
    category: "Bathroom",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    description: "Spa-inspired bathroom remodel with freestanding tub and walk-in shower.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
    ],
    budget: "$18,000 - $28,000",
    spaceType: "Residential",
    duration: "3 weeks",
    serviceScope: ["Tile Work", "Plumbing", "Freestanding Tub", "Walk-in Shower", "Vanity"],
    challenge: "The master bathroom felt cramped and outdated, with a bulky built-in tub taking up too much space.",
    solution: "We replaced the built-in tub with an elegant freestanding soaker tub, added a frameless glass walk-in shower, and used spa-inspired natural stone tiles.",
  },
  {
    title: "Bathroom Vanity Renovation in West Vancouver",
    category: "Bathroom",
    location: "West Vancouver",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
    description: "Custom vanity installation with premium fixtures in a luxury home.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
    ],
    budget: "$10,000 - $18,000",
    spaceType: "Luxury Residential",
    duration: "2 weeks",
    serviceScope: ["Custom Vanity", "Fixtures", "Mirror", "Lighting"],
    challenge: "The luxury home required a custom vanity that matched the high-end aesthetic while providing ample storage for a busy family.",
    solution: "We designed and built a custom double-sink vanity with solid wood construction, paired with designer fixtures and a backlit mirror for a sophisticated look.",
  },
  {
    title: "Stunning Home Renovation in Langley",
    category: "Whole House",
    location: "Langley",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
    description: "Full-scale home transformation including kitchen, bathrooms, and living spaces.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$80,000 - $120,000",
    spaceType: "Residential",
    duration: "10 weeks",
    serviceScope: ["Kitchen", "Bathrooms", "Flooring", "Painting", "Lighting", "Living Spaces"],
    challenge: "A 30-year-old home with outdated finishes throughout, requiring a complete modernization while the family continued to live on-site.",
    solution: "We phased the renovation room by room, starting with the kitchen and bathrooms, then moving to living areas — minimizing disruption while delivering a cohesive modern transformation.",
  },
  {
    title: "Surrey Home Before and After",
    category: "Whole House",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
    description: "Dramatic whole house renovation showcasing the complete transformation.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    ],
    budget: "$60,000 - $90,000",
    spaceType: "Residential",
    duration: "8 weeks",
    serviceScope: ["Kitchen", "Bathrooms", "Flooring", "Painting", "Electrical"],
    challenge: "A neglected property with severely dated interiors, requiring both cosmetic and structural updates to bring it up to modern standards.",
    solution: "We addressed structural issues first, then completely refreshed every room with new flooring, modern fixtures, fresh paint, and updated electrical throughout.",
  },
  {
    title: "Commercial Renovation - Skin Lab Granville",
    category: "Commercial",
    location: "Vancouver",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/84.jpg",
    description: "Professional commercial space renovation for a skincare clinic on Granville.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/84.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$50,000 - $75,000",
    spaceType: "Commercial",
    duration: "6 weeks",
    serviceScope: ["Interior Build-out", "Plumbing", "Electrical", "Custom Millwork", "Painting"],
    challenge: "Converting a raw commercial shell into a premium skincare clinic that meets health code requirements while projecting a luxurious brand image.",
    solution: "We designed a clean, clinical yet luxurious interior with custom treatment rooms, specialized plumbing for treatment stations, and a welcoming reception area that reflects the brand.",
  },
  {
    title: "Richmond Kitchen Remodel & Bath",
    category: "Whole House",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    description: "Combined kitchen remodel and bathroom renovation for a complete home upgrade.",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    ],
    budget: "$35,000 - $55,000",
    spaceType: "Residential",
    duration: "6 weeks",
    serviceScope: ["Kitchen Remodel", "Bathroom Renovation", "Flooring", "Countertops"],
    challenge: "The homeowner needed both the kitchen and bathroom updated on a moderate budget without compromising on quality.",
    solution: "We sourced high-quality materials at competitive prices and coordinated both renovations to run in parallel, delivering premium results within the budget.",
  },
];

const projectsZh: Project[] = [
  {
    title: "高贵林 - 白色摇门橱柜",
    category: "厨房",
    location: "Coquitlam",
    image: "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
    description: "现代白色摇门橱柜安装，配备高端台面和后挡板。",
    badge: "New",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
    ],
    budget: "$15,000 - $25,000",
    spaceType: "住宅",
    duration: "3周",
    serviceScope: ["橱柜", "台面", "后挡板"],
    challenge: "原有厨房配备过时的橡木橱柜，台面空间有限，使厨房显得狭窄而阴暗。",
    solution: "我们安装了明亮的白色摇门橱柜配备缓冲五金件，搭配石英台面和现代瓷砖后挡板，使空间更加开阔。",
  },
  {
    title: "列治文厨房和浴室改造",
    category: "厨房",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
    description: "采用现代风格完成厨房和浴室全面改造。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$30,000 - $45,000",
    spaceType: "公寓",
    duration: "5周",
    serviceScope: ["橱柜", "台面", "地板", "水管", "瓷砖"],
    challenge: "一套过时的公寓，厨房和浴室都需要在紧迫的时间内进行统一的现代化更新。",
    solution: "我们协调厨房和浴室的施工同步进行，采用统一的现代色调搭配石英台面和时尚洁具。",
  },
  {
    title: "素里住宅装修",
    category: "厨房",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    description: "全屋装修，包括令人惊叹的厨房重新设计。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
    ],
    budget: "$40,000 - $60,000",
    spaceType: "住宅",
    duration: "6周",
    serviceScope: ["厨房设计", "橱柜", "台面", "地板", "油漆"],
    challenge: "一栋老旧的素里住宅需要全面翻新厨房，同时保持开放式客厅的结构完整性和动线。",
    solution: "我们重新设计了厨房布局以优化工作流程，安装了定制橱柜，选择了耐用又美观的材料来配合开放式设计。",
  },
  {
    title: "素里白色调厨房",
    category: "厨房",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
    description: "优雅的白色调厨房装修，线条简洁，配备现代家电。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
      "https://reno-stars.com/wp-content/uploads/2025/02/微信图片_20250228155837.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    ],
    budget: "$20,000 - $35,000",
    spaceType: "住宅",
    duration: "4周",
    serviceScope: ["橱柜", "台面", "家电安装", "灯光"],
    challenge: "业主想要一个明亮通风的厨房，但现有布局采光不足且装饰色调偏暗。",
    solution: "我们采用全白色调搭配橱柜下方LED灯带、反光石英台面和合理布置的筒灯，最大限度提升亮度。",
  },
  {
    title: "三角洲厨房装修",
    category: "厨房",
    location: "Delta",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
    description: "现代厨房装修，配备定制橱柜和石英台面。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/340.png",
    ],
    budget: "$25,000 - $40,000",
    spaceType: "住宅",
    duration: "4周",
    serviceScope: ["橱柜", "台面", "后挡板", "水管"],
    challenge: "台面空间有限且家电过时，对于五口之家来说厨房效率低下。",
    solution: "我们重新规划布局，增加了带额外储物空间的岛台，安装了石英台面和现代瓷砖后挡板，打造实用的家庭厨房。",
  },
  {
    title: "列治文现代厨房装修",
    category: "厨房",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
    description: "全面的现代厨房装修，配备岛台和高端设备。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/75-1.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/73.png",
    ],
    budget: "$35,000 - $50,000",
    spaceType: "住宅",
    duration: "5周",
    serviceScope: ["厨房设计", "橱柜", "台面", "岛台", "洁具"],
    challenge: "业主想要一个带岛台的专业级厨房，但现有空间有承重墙限制了布局选择。",
    solution: "我们与结构工程师合作安全地打通空间，然后安装了大型瀑布边岛台、高端橱柜和专业级洁具。",
  },
  {
    title: "三角洲浴室装修",
    category: "卫浴",
    location: "Delta",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
    description: "完整的浴室装修，配备豪华瓷砖和现代洗手台。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    ],
    budget: "$12,000 - $20,000",
    spaceType: "住宅",
    duration: "2周",
    serviceScope: ["瓷砖", "洗手台", "水管", "灯光"],
    challenge: "小浴室存在水损问题，布局不合理浪费了宝贵的地面空间。",
    solution: "我们修复了水损，重新规划布局改为步入式淋浴，安装了大尺寸瓷砖和悬浮洗手台，营造宽敞感。",
  },
  {
    title: "列治文浴室改造",
    category: "卫浴",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    description: "水疗风格浴室改造，配备独立浴缸和步入式淋浴。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
    ],
    budget: "$18,000 - $28,000",
    spaceType: "住宅",
    duration: "3周",
    serviceScope: ["瓷砖", "水管", "独立浴缸", "步入式淋浴", "洗手台"],
    challenge: "主卫感觉局促过时，笨重的内嵌浴缸占用了太多空间。",
    solution: "我们用优雅的独立泡澡浴缸替换了内嵌浴缸，增加了无框玻璃步入式淋浴，采用水疗风格天然石材瓷砖。",
  },
  {
    title: "西温浴室洗手台装修",
    category: "卫浴",
    location: "West Vancouver",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
    description: "豪宅中的定制洗手台安装，配备高端洁具。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/16.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/71.png",
    ],
    budget: "$10,000 - $18,000",
    spaceType: "豪华住宅",
    duration: "2周",
    serviceScope: ["定制洗手台", "洁具", "镜子", "灯光"],
    challenge: "豪宅需要一个与高端美学相匹配的定制洗手台，同时为繁忙的家庭提供充足的储物空间。",
    solution: "我们设计并制作了实木双盆定制洗手台，搭配设计师洁具和背光镜，打造精致外观。",
  },
  {
    title: "兰里全屋翻新",
    category: "全屋",
    location: "Langley",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
    description: "全方位家居改造，包括厨房、浴室和起居空间。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$80,000 - $120,000",
    spaceType: "住宅",
    duration: "10周",
    serviceScope: ["厨房", "浴室", "地板", "油漆", "灯光", "起居空间"],
    challenge: "一栋30年老屋，全屋装修过时，需要在家庭继续居住的情况下进行全面现代化改造。",
    solution: "我们分阶段逐房间施工，从厨房和浴室开始，再到起居空间——最大限度减少干扰，同时实现统一的现代化改造。",
  },
  {
    title: "素里住宅前后对比",
    category: "全屋",
    location: "Surrey",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
    description: "震撼的全屋装修，展示完整的蜕变过程。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/53.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/15.png",
    ],
    budget: "$60,000 - $90,000",
    spaceType: "住宅",
    duration: "8周",
    serviceScope: ["厨房", "浴室", "地板", "油漆", "电气"],
    challenge: "一处被忽视的房产，室内严重过时，需要外观和结构两方面的更新才能达到现代标准。",
    solution: "我们先处理结构问题，然后对每个房间进行全面翻新——新地板、现代洁具、新鲜油漆和全屋电气升级。",
  },
  {
    title: "商业装修 - Skin Lab Granville",
    category: "商业",
    location: "Vancouver",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/84.jpg",
    description: "Granville街护肤诊所的专业商业空间装修。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/84.jpg",
      "https://reno-stars.com/wp-content/uploads/2025/04/49.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    ],
    budget: "$50,000 - $75,000",
    spaceType: "商业",
    duration: "6周",
    serviceScope: ["室内装修", "水管", "电气", "定制木工", "油漆"],
    challenge: "将一个毛坯商业空间改造成符合卫生规范要求的高端护肤诊所，同时展现奢华品牌形象。",
    solution: "我们设计了简洁临床又不失奢华的室内空间，包含定制治疗室、专业水管设施和体现品牌特色的温馨接待区。",
  },
  {
    title: "列治文厨房和浴室改造",
    category: "全屋",
    location: "Richmond",
    image: "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
    description: "厨房和浴室联合改造，实现全屋升级。",
    gallery: [
      "https://reno-stars.com/wp-content/uploads/2025/04/52.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/35.png",
      "https://reno-stars.com/wp-content/uploads/2025/04/主卫.jpg",
    ],
    budget: "$35,000 - $55,000",
    spaceType: "住宅",
    duration: "6周",
    serviceScope: ["厨房改造", "浴室装修", "地板", "台面"],
    challenge: "业主需要在有限预算内同时更新厨房和浴室，且不降低质量标准。",
    solution: "我们以有竞争力的价格采购优质材料，并协调两项装修同步进行，在预算内交付高品质成果。",
  },
];

export function getLocalizedProjects(lang: string) {
  if (lang === 'zh') {
    return { categories: categoriesZh, projects: projectsZh };
  }
  return { categories, projects };
}
