-- Migration: blog_posts — service coverage gap audit
-- Date: 2026-08-24
-- Status: NOT APPLIED — this is an audit record, not a data-change migration
-- Topic: DOCUMENTATION ONLY
-- Source: DB query against services + blog_posts tables (2026-08-24)
--
-- COVERAGE AUDIT RESULT:
-- 5 of 11 services have ZERO published blog posts:
--   accessible-bathroom  — 0 published posts
--   basement            — 0 published posts
--   poly-b-replacement  — 0 published posts
--   cabinet             — 0 published posts
--   critical-load-panel  — 0 published posts
--
-- 6 of 11 services have published blog coverage:
--   heat-pump-hvac     — 1+ post (pending: heat-pump-installation-vancouver-2026)
--   kitchen-renovation  — covered
--   bathroom-renovation — covered
--   whole-house-renovation — covered
--   commercial-renovation — covered
--   windows-doors      — covered
--
-- RECOMMENDED ACTIONS (not encoded here — human decision required):
--   1. accessible-bathroom  → "accessible bathroom renovation Vancouver" post
--   2. basement            → "basement renovation Vancouver legal suite" post
--   3. poly-b-replacement  → "Poly-B pipe replacement Vancouver" post
--   4. cabinet             → "cabinet refacing Vancouver" post
--   5. critical-load-panel → "electrical panel upgrade Vancouver" post
--
-- This file is a documentation artifact. No data changes are encoded.
