/**
 * Shape of data/site-visit/catalog.json — generated by
 * reno-stars-invoice-service/tools/export-site-visit-catalog.ts and pulled in
 * by scripts/sync-site-visit-catalog.mjs.
 *
 * Keep in step with the exporter. `SCHEMA_VERSION` guards the pair: the sync
 * script refuses a file whose version doesn't match.
 */

export const SCHEMA_VERSION = 1;

/** A single step the quote will contain, e.g. "vanity" or "showerBase". */
export interface CatalogStep {
  key: string;
  order: number;
  /** Rendered quote line, shown as context on the checklist card. */
  text: string;
  remarks: string[];
  /**
   * Step-class fields the quoting code leaves null. These are precisely the
   * values a site visit has to bring back, so the UI promotes them.
   */
  captureFields: string[];
}

export interface CatalogModel {
  id: string;
  name: string;
  code: string;
  steps: string[];
}

export interface CatalogModifier {
  id: string;
  name: string;
  kind: 'addon' | 'replacement';
  addsSteps: string[];
  removesSteps: string[];
  /** Modifier only edits existing steps — no step enters or leaves scope. */
  mutatesOnly: boolean;
  error?: string;
}

export interface CatalogSection {
  id: string;
  name: string;
  baselineModel: string;
  models: CatalogModel[];
  modifiers: CatalogModifier[];
  /** step key → things the client supplies when that step is in scope. */
  clientProvides: Record<string, string[]>;
}

export interface SiteVisitCatalog {
  schemaVersion: number;
  generatedBy: string;
  sections: CatalogSection[];
  steps: CatalogStep[];
}

/** One section's picks. A visit can carry one of these per section. */
export interface SectionSelection {
  sectionId: string;
  modelId: string;
  addonIds: string[];
}

/** A step that made it into scope, with why it's there. */
export interface ResolvedStep extends CatalogStep {
  sectionId: string;
  /** Modifier ids that pulled this step in; empty when the model carries it. */
  addedBy: string[];
}

export interface ResolvedScope {
  steps: ResolvedStep[];
  /** Deduped list of things the client supplies, across all sections. */
  clientProvides: string[];
}
